class CountriesEntity {
  final String code;
  final String name;

  CountriesEntity({required this.code, required this.name});
}

final List<CountriesEntity> countriesList = [
  CountriesEntity(code: "AW", name: "Aruba"),
  CountriesEntity(code: "AF", name: "Afghanistan"),
  CountriesEntity(code: "AO", name: "Angola"),
  CountriesEntity(code: "AI", name: "Anguilla"),
  CountriesEntity(code: "AX", name: "Åland Islands"),
  CountriesEntity(code: "AL", name: "Albania"),
  CountriesEntity(code: "AD", name: "Andorra"),
  CountriesEntity(code: "AE", name: "United Arab Emirates"),
  CountriesEntity(code: "AR", name: "Argentina"),
  CountriesEntity(code: "AM", name: "Armenia"),
  CountriesEntity(code: "AS", name: "American Samoa"),
  CountriesEntity(code: "AQ", name: "Antarctica"),
  CountriesEntity(code: "TF", name: "French Southern Territories"),
  CountriesEntity(code: "AG", name: "Antigua and Barbuda"),
  CountriesEntity(code: "AU", name: "Australia"),
  CountriesEntity(code: "AT", name: "Austria"),
  CountriesEntity(code: "AZ", name: "Azerbaijan"),
  CountriesEntity(code: "BI", name: "Burundi"),
  CountriesEntity(code: "BE", name: "Belgium"),
  CountriesEntity(code: "BJ", name: "Benin"),
  CountriesEntity(code: "BQ", name: "Bonaire, Sint Eustatius and Saba"),
  CountriesEntity(code: "BF", name: "Burkina Faso"),
  CountriesEntity(code: "BD", name: "Bangladesh"),
  CountriesEntity(code: "BG", name: "Bulgaria"),
  CountriesEntity(code: "BH", name: "Bahrain"),
  CountriesEntity(code: "BS", name: "Bahamas"),
  CountriesEntity(code: "BA", name: "Bosnia and Herzegovina"),
  CountriesEntity(code: "BL", name: "Saint Barthélemy"),
  CountriesEntity(code: "BY", name: "Belarus"),
  CountriesEntity(code: "BZ", name: "Belize"),
  CountriesEntity(code: "BM", name: "Bermuda"),
  CountriesEntity(code: "BO", name: "Bolivia, Plurinational State of"),
  CountriesEntity(code: "BR", name: "Brazil"),
  CountriesEntity(code: "BB", name: "Barbados"),
  CountriesEntity(code: "BN", name: "Brunei Darussalam"),
  CountriesEntity(code: "BT", name: "Bhutan"),
  CountriesEntity(code: "BV", name: "Bouvet Island"),
  CountriesEntity(code: "BW", name: "Botswana"),
  CountriesEntity(code: "CF", name: "Central African Republic"),
  CountriesEntity(code: "CA", name: "Canada"),
  CountriesEntity(code: "CC", name: "Cocos (Keeling) Islands"),
  CountriesEntity(code: "CH", name: "Switzerland"),
  CountriesEntity(code: "CL", name: "Chile"),
  CountriesEntity(code: "CN", name: "China"),
  CountriesEntity(code: "CI", name: "Côte d'Ivoire"),
  CountriesEntity(code: "CM", name: "Cameroon"),
  CountriesEntity(code: "CD", name: "Congo, The Democratic Republic of the"),
  CountriesEntity(code: "CG", name: "Congo"),
  CountriesEntity(code: "CK", name: "Cook Islands"),
  CountriesEntity(code: "CO", name: "Colombia"),
  CountriesEntity(code: "KM", name: "Comoros"),
  CountriesEntity(code: "CV", name: "Cabo Verde"),
  CountriesEntity(code: "CR", name: "Costa Rica"),
  CountriesEntity(code: "CU", name: "Cuba"),
  CountriesEntity(code: "CW", name: "Curaçao"),
  CountriesEntity(code: "CX", name: "Christmas Island"),
  CountriesEntity(code: "KY", name: "Cayman Islands"),
  CountriesEntity(code: "CY", name: "Cyprus"),
  CountriesEntity(code: "CZ", name: "Czechia"),
  CountriesEntity(code: "DE", name: "Germany"),
  CountriesEntity(code: "DJ", name: "Djibouti"),
  CountriesEntity(code: "DM", name: "Dominica"),
  CountriesEntity(code: "DK", name: "Denmark"),
  CountriesEntity(code: "DO", name: "Dominican Republic"),
  CountriesEntity(code: "DZ", name: "Algeria"),
  CountriesEntity(code: "EC", name: "Ecuador"),
  CountriesEntity(code: "EG", name: "Egypt"),
  CountriesEntity(code: "ER", name: "Eritrea"),
  CountriesEntity(code: "EH", name: "Western Sahara"),
  CountriesEntity(code: "ES", name: "Spain"),
  CountriesEntity(code: "EE", name: "Estonia"),
  CountriesEntity(code: "ET", name: "Ethiopia"),
  CountriesEntity(code: "FI", name: "Finland"),
  CountriesEntity(code: "FJ", name: "Fiji"),
  CountriesEntity(code: "FK", name: "Falkland Islands (Malvinas)"),
  CountriesEntity(code: "FR", name: "France"),
  CountriesEntity(code: "FO", name: "Faroe Islands"),
  CountriesEntity(code: "FM", name: "Micronesia, Federated States of"),
  CountriesEntity(code: "GA", name: "Gabon"),
  CountriesEntity(code: "GB", name: "United Kingdom"),
  CountriesEntity(code: "GE", name: "Georgia"),
  CountriesEntity(code: "GG", name: "Guernsey"),
  CountriesEntity(code: "GH", name: "Ghana"),
  CountriesEntity(code: "GI", name: "Gibraltar"),
  CountriesEntity(code: "GN", name: "Guinea"),
  CountriesEntity(code: "GP", name: "Guadeloupe"),
  CountriesEntity(code: "GM", name: "Gambia"),
  CountriesEntity(code: "GW", name: "Guinea-Bissau"),
  CountriesEntity(code: "GQ", name: "Equatorial Guinea"),
  CountriesEntity(code: "GR", name: "Greece"),
  CountriesEntity(code: "GD", name: "Grenada"),
  CountriesEntity(code: "GL", name: "Greenland"),
  CountriesEntity(code: "GT", name: "Guatemala"),
  CountriesEntity(code: "GF", name: "French Guiana"),
  CountriesEntity(code: "GU", name: "Guam"),
  CountriesEntity(code: "GY", name: "Guyana"),
  CountriesEntity(code: "HK", name: "Hong Kong"),
  CountriesEntity(code: "HM", name: "Heard Island and McDonald Islands"),
  CountriesEntity(code: "HN", name: "Honduras"),
  CountriesEntity(code: "HR", name: "Croatia"),
  CountriesEntity(code: "HT", name: "Haiti"),
  CountriesEntity(code: "HU", name: "Hungary"),
  CountriesEntity(code: "ID", name: "Indonesia"),
  CountriesEntity(code: "IM", name: "Isle of Man"),
  CountriesEntity(code: "IN", name: "India"),
  CountriesEntity(code: "IO", name: "British Indian Ocean Territory"),
  CountriesEntity(code: "IE", name: "Ireland"),
  CountriesEntity(code: "IR", name: "Iran, Islamic Republic of"),
  CountriesEntity(code: "IQ", name: "Iraq"),
  CountriesEntity(code: "IS", name: "Iceland"),
  CountriesEntity(code: "IL", name: "Israel"),
  CountriesEntity(code: "IT", name: "Italy"),
  CountriesEntity(code: "JM", name: "Jamaica"),
  CountriesEntity(code: "JE", name: "Jersey"),
  CountriesEntity(code: "JO", name: "Jordan"),
  CountriesEntity(code: "JP", name: "Japan"),
  CountriesEntity(code: "KZ", name: "Kazakhstan"),
  CountriesEntity(code: "KE", name: "Kenya"),
  CountriesEntity(code: "KG", name: "Kyrgyzstan"),
  CountriesEntity(code: "KH", name: "Cambodia"),
  CountriesEntity(code: "KI", name: "Kiribati"),
  CountriesEntity(code: "KN", name: "Saint Kitts and Nevis"),
  CountriesEntity(code: "KR", name: "Korea, Republic of"),
  CountriesEntity(code: "KW", name: "Kuwait"),
  CountriesEntity(code: "LA", name: "Lao People's Democratic Republic"),
  CountriesEntity(code: "LB", name: "Lebanon"),
  CountriesEntity(code: "LR", name: "Liberia"),
  CountriesEntity(code: "LY", name: "Libya"),
  CountriesEntity(code: "LC", name: "Saint Lucia"),
  CountriesEntity(code: "LI", name: "Liechtenstein"),
  CountriesEntity(code: "LK", name: "Sri Lanka"),
  CountriesEntity(code: "LS", name: "Lesotho"),
  CountriesEntity(code: "LT", name: "Lithuania"),
  CountriesEntity(code: "LU", name: "Luxembourg"),
  CountriesEntity(code: "LV", name: "Latvia"),
  CountriesEntity(code: "MO", name: "Macao"),
  CountriesEntity(code: "MF", name: "Saint Martin (French part)"),
  CountriesEntity(code: "MA", name: "Morocco"),
  CountriesEntity(code: "MC", name: "Monaco"),
  CountriesEntity(code: "MD", name: "Moldova, Republic of"),
  CountriesEntity(code: "MG", name: "Madagascar"),
  CountriesEntity(code: "MV", name: "Maldives"),
  CountriesEntity(code: "MX", name: "Mexico"),
  CountriesEntity(code: "MH", name: "Marshall Islands"),
  CountriesEntity(code: "MK", name: "North Macedonia"),
  CountriesEntity(code: "ML", name: "Mali"),
  CountriesEntity(code: "MT", name: "Malta"),
  CountriesEntity(code: "MM", name: "Myanmar"),
  CountriesEntity(code: "ME", name: "Montenegro"),
  CountriesEntity(code: "MN", name: "Mongolia"),
  CountriesEntity(code: "MP", name: "Northern Mariana Islands"),
  CountriesEntity(code: "MZ", name: "Mozambique"),
  CountriesEntity(code: "MR", name: "Mauritania"),
  CountriesEntity(code: "MS", name: "Montserrat"),
  CountriesEntity(code: "MQ", name: "Martinique"),
  CountriesEntity(code: "MU", name: "Mauritius"),
  CountriesEntity(code: "MW", name: "Malawi"),
  CountriesEntity(code: "MY", name: "Malaysia"),
  CountriesEntity(code: "YT", name: "Mayotte"),
  CountriesEntity(code: "NA", name: "Namibia"),
  CountriesEntity(code: "NC", name: "New Caledonia"),
  CountriesEntity(code: "NE", name: "Niger"),
  CountriesEntity(code: "NF", name: "Norfolk Island"),
  CountriesEntity(code: "NG", name: "Nigeria"),
  CountriesEntity(code: "NI", name: "Nicaragua"),
  CountriesEntity(code: "NU", name: "Niue"),
  CountriesEntity(code: "NL", name: "Netherlands"),
  CountriesEntity(code: "NO", name: "Norway"),
  CountriesEntity(code: "NP", name: "Nepal"),
  CountriesEntity(code: "NR", name: "Nauru"),
  CountriesEntity(code: "NZ", name: "New Zealand"),
  CountriesEntity(code: "OM", name: "Oman"),
  CountriesEntity(code: "PK", name: "Pakistan"),
  CountriesEntity(code: "PA", name: "Panama"),
  CountriesEntity(code: "PN", name: "Pitcairn"),
  CountriesEntity(code: "PE", name: "Peru"),
  CountriesEntity(code: "PH", name: "Philippines"),
  CountriesEntity(code: "PW", name: "Palau"),
  CountriesEntity(code: "PG", name: "Papua New Guinea"),
  CountriesEntity(code: "PL", name: "Poland"),
  CountriesEntity(code: "PR", name: "Puerto Rico"),
  CountriesEntity(code: "KP", name: "Korea, Democratic People's Republic of"),
  CountriesEntity(code: "PT", name: "Portugal"),
  CountriesEntity(code: "PY", name: "Paraguay"),
  CountriesEntity(code: "PS", name: "Palestine, State of"),
  CountriesEntity(code: "PF", name: "French Polynesia"),
  CountriesEntity(code: "QA", name: "Qatar"),
  CountriesEntity(code: "RE", name: "Réunion"),
  CountriesEntity(code: "RO", name: "Romania"),
  CountriesEntity(code: "RU", name: "Russian Federation"),
  CountriesEntity(code: "RW", name: "Rwanda"),
  CountriesEntity(code: "SA", name: "Saudi Arabia"),
  CountriesEntity(code: "SD", name: "Sudan"),
  CountriesEntity(code: "SN", name: "Senegal"),
  CountriesEntity(code: "SG", name: "Singapore"),
  CountriesEntity(
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
  ),
  CountriesEntity(
    code: "SH",
    name: "Saint Helena, Ascension and Tristan da Cunha",
  ),
  CountriesEntity(code: "SJ", name: "Svalbard and Jan Mayen"),
  CountriesEntity(code: "SB", name: "Solomon Islands"),
  CountriesEntity(code: "SL", name: "Sierra Leone"),
  CountriesEntity(code: "SV", name: "El Salvador"),
  CountriesEntity(code: "SM", name: "San Marino"),
  CountriesEntity(code: "SO", name: "Somalia"),
  CountriesEntity(code: "PM", name: "Saint Pierre and Miquelon"),
  CountriesEntity(code: "RS", name: "Serbia"),
  CountriesEntity(code: "SS", name: "South Sudan"),
  CountriesEntity(code: "ST", name: "Sao Tome and Principe"),
  CountriesEntity(code: "SR", name: "Suriname"),
  CountriesEntity(code: "SK", name: "Slovakia"),
  CountriesEntity(code: "SI", name: "Slovenia"),
  CountriesEntity(code: "SE", name: "Sweden"),
  CountriesEntity(code: "SZ", name: "Eswatini"),
  CountriesEntity(code: "SX", name: "Sint Maarten (Dutch part)"),
  CountriesEntity(code: "SC", name: "Seychelles"),
  CountriesEntity(code: "SY", name: "Syrian Arab Republic"),
  CountriesEntity(code: "TC", name: "Turks and Caicos Islands"),
  CountriesEntity(code: "TD", name: "Chad"),
  CountriesEntity(code: "TG", name: "Togo"),
  CountriesEntity(code: "TH", name: "Thailand"),
  CountriesEntity(code: "TJ", name: "Tajikistan"),
  CountriesEntity(code: "TK", name: "Tokelau"),
  CountriesEntity(code: "TM", name: "Turkmenistan"),
  CountriesEntity(code: "TL", name: "Timor-Leste"),
  CountriesEntity(code: "TO", name: "Tonga"),
  CountriesEntity(code: "TT", name: "Trinidad and Tobago"),
  CountriesEntity(code: "TN", name: "Tunisia"),
  CountriesEntity(code: "TR", name: "Turkey"),
  CountriesEntity(code: "TV", name: "Tuvalu"),
  CountriesEntity(code: "TW", name: "Taiwan, Province of China"),
  CountriesEntity(code: "TZ", name: "Tanzania, United Republic of"),
  CountriesEntity(code: "UG", name: "Uganda"),
  CountriesEntity(code: "UA", name: "Ukraine"),
  CountriesEntity(code: "UM", name: "United States Minor Outlying Islands"),
  CountriesEntity(code: "UY", name: "Uruguay"),
  CountriesEntity(code: "US", name: "United States"),
  CountriesEntity(code: "UZ", name: "Uzbekistan"),
  CountriesEntity(code: "VA", name: "Holy See (Vatican City State)"),
  CountriesEntity(code: "VC", name: "Saint Vincent and the Grenadines"),
  CountriesEntity(code: "VE", name: "Venezuela, Bolivarian Republic of"),
  CountriesEntity(code: "VG", name: "Virgin Islands, British"),
  CountriesEntity(code: "VI", name: "Virgin Islands, U.S."),
  CountriesEntity(code: "VN", name: "Viet Nam"),
  CountriesEntity(code: "VU", name: "Vanuatu"),
  CountriesEntity(code: "WF", name: "Wallis and Futuna"),
  CountriesEntity(code: "WS", name: "Samoa"),
  CountriesEntity(code: "YE", name: "Yemen"),
  CountriesEntity(code: "ZA", name: "South Africa"),
  CountriesEntity(code: "ZM", name: "Zambia"),
  CountriesEntity(code: "ZW", name: "Zimbabwe"),
];
