// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-CXm7h8koHDE9xgiECiVCPHwQNW2EVWk',
    appId: '1:460652815575:web:15db44d343a58f20377c92',
    messagingSenderId: '460652815575',
    projectId: 'bingo-ad890',
    authDomain: 'bingo-ad890.firebaseapp.com',
    storageBucket: 'bingo-ad890.firebasestorage.app',
    measurementId: 'G-9QL3MZGV4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkBApKtmSAkdujWlldIMb_A8e5L-0vOCI',
    appId: '1:460652815575:android:a8f3a93b6584b46c377c92',
    messagingSenderId: '460652815575',
    projectId: 'bingo-ad890',
    storageBucket: 'bingo-ad890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiCc9yp14g-PXC7bnn_NmFMyTHeKmcq5E',
    appId: '1:460652815575:ios:ab67aa9c6ddabbf5377c92',
    messagingSenderId: '460652815575',
    projectId: 'bingo-ad890',
    storageBucket: 'bingo-ad890.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiCc9yp14g-PXC7bnn_NmFMyTHeKmcq5E',
    appId: '1:460652815575:ios:ab67aa9c6ddabbf5377c92',
    messagingSenderId: '460652815575',
    projectId: 'bingo-ad890',
    storageBucket: 'bingo-ad890.firebasestorage.app',
    iosBundleId: 'com.example.bingo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-CXm7h8koHDE9xgiECiVCPHwQNW2EVWk',
    appId: '1:460652815575:web:ae98406bc3e6abf8377c92',
    messagingSenderId: '460652815575',
    projectId: 'bingo-ad890',
    authDomain: 'bingo-ad890.firebaseapp.com',
    storageBucket: 'bingo-ad890.firebasestorage.app',
    measurementId: 'G-G7BWEEL0XK',
  );
}
